// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `now_ms`, `random_token`, `run_bootstrap`, `run_echo`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

String ping() => RustLib.instance.api.crateApiPing();

Future<BootstrapResult> bootstrap(
        {required String relayUrl,
        required String serverNpub,
        required PlatformInt64 timeoutMs,
        required bool connectMode}) =>
    RustLib.instance.api.crateApiBootstrap(
        relayUrl: relayUrl,
        serverNpub: serverNpub,
        timeoutMs: timeoutMs,
        connectMode: connectMode);

Future<EchoResult> echoTest(
        {required String relayUrl,
        required String serverNpub,
        required PlatformInt64 timeoutMs}) =>
    RustLib.instance.api.crateApiEchoTest(
        relayUrl: relayUrl, serverNpub: serverNpub, timeoutMs: timeoutMs);

class BootstrapResult {
  final PlatformInt64 bootstrapRttMs;
  final String relayUrl;
  final String serverNpub;
  final String clientNpub;
  final ServerInfo serverInfo;

  const BootstrapResult({
    required this.bootstrapRttMs,
    required this.relayUrl,
    required this.serverNpub,
    required this.clientNpub,
    required this.serverInfo,
  });

  @override
  int get hashCode =>
      bootstrapRttMs.hashCode ^
      relayUrl.hashCode ^
      serverNpub.hashCode ^
      clientNpub.hashCode ^
      serverInfo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BootstrapResult &&
          runtimeType == other.runtimeType &&
          bootstrapRttMs == other.bootstrapRttMs &&
          relayUrl == other.relayUrl &&
          serverNpub == other.serverNpub &&
          clientNpub == other.clientNpub &&
          serverInfo == other.serverInfo;
}

class EchoResult {
  final bool echoRoundtripOk;
  final PlatformInt64? echoRttMs;
  final Endpoint endpoint;
  final String detail;

  const EchoResult({
    required this.echoRoundtripOk,
    this.echoRttMs,
    required this.endpoint,
    required this.detail,
  });

  @override
  int get hashCode =>
      echoRoundtripOk.hashCode ^
      echoRttMs.hashCode ^
      endpoint.hashCode ^
      detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EchoResult &&
          runtimeType == other.runtimeType &&
          echoRoundtripOk == other.echoRoundtripOk &&
          echoRttMs == other.echoRttMs &&
          endpoint == other.endpoint &&
          detail == other.detail;
}

class Endpoint {
  final String host;
  final int port;

  const Endpoint({
    required this.host,
    required this.port,
  });

  @override
  int get hashCode => host.hashCode ^ port.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Endpoint &&
          runtimeType == other.runtimeType &&
          host == other.host &&
          port == other.port;
}

class Punch {
  final PlatformInt64 startAtMs;
  final BigInt intervalMs;
  final BigInt durationMs;

  const Punch({
    required this.startAtMs,
    required this.intervalMs,
    required this.durationMs,
  });

  @override
  int get hashCode =>
      startAtMs.hashCode ^ intervalMs.hashCode ^ durationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Punch &&
          runtimeType == other.runtimeType &&
          startAtMs == other.startAtMs &&
          intervalMs == other.intervalMs &&
          durationMs == other.durationMs;
}

class ServerInfo {
  final String msgType;
  final String version;
  final String sessionId;
  final String nonce;
  final PlatformInt64 issuedAt;
  final Endpoint endpoint;
  final Punch? punch;
  final StunInfo? stun;

  const ServerInfo({
    required this.msgType,
    required this.version,
    required this.sessionId,
    required this.nonce,
    required this.issuedAt,
    required this.endpoint,
    this.punch,
    this.stun,
  });

  @override
  int get hashCode =>
      msgType.hashCode ^
      version.hashCode ^
      sessionId.hashCode ^
      nonce.hashCode ^
      issuedAt.hashCode ^
      endpoint.hashCode ^
      punch.hashCode ^
      stun.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerInfo &&
          runtimeType == other.runtimeType &&
          msgType == other.msgType &&
          version == other.version &&
          sessionId == other.sessionId &&
          nonce == other.nonce &&
          issuedAt == other.issuedAt &&
          endpoint == other.endpoint &&
          punch == other.punch &&
          stun == other.stun;
}

class StunInfo {
  final String uri;
  final String? metadataTag;

  const StunInfo({
    required this.uri,
    this.metadataTag,
  });

  @override
  int get hashCode => uri.hashCode ^ metadataTag.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StunInfo &&
          runtimeType == other.runtimeType &&
          uri == other.uri &&
          metadataTag == other.metadataTag;
}
