// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 569448596;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'fips_mobile_core',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<BootstrapResult> crateApiBootstrap(
      {required String relayUrl,
      required String serverNpub,
      required PlatformInt64 timeoutMs,
      required bool connectMode});

  Future<EchoResult> crateApiEchoTest(
      {required String relayUrl,
      required String serverNpub,
      required PlatformInt64 timeoutMs});

  String crateApiPing();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<BootstrapResult> crateApiBootstrap(
      {required String relayUrl,
      required String serverNpub,
      required PlatformInt64 timeoutMs,
      required bool connectMode}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(relayUrl, serializer);
        sse_encode_String(serverNpub, serializer);
        sse_encode_i_64(timeoutMs, serializer);
        sse_encode_bool(connectMode, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bootstrap_result,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiBootstrapConstMeta,
      argValues: [relayUrl, serverNpub, timeoutMs, connectMode],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiBootstrapConstMeta => const TaskConstMeta(
        debugName: "bootstrap",
        argNames: ["relayUrl", "serverNpub", "timeoutMs", "connectMode"],
      );

  @override
  Future<EchoResult> crateApiEchoTest(
      {required String relayUrl,
      required String serverNpub,
      required PlatformInt64 timeoutMs}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(relayUrl, serializer);
        sse_encode_String(serverNpub, serializer);
        sse_encode_i_64(timeoutMs, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_echo_result,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiEchoTestConstMeta,
      argValues: [relayUrl, serverNpub, timeoutMs],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEchoTestConstMeta => const TaskConstMeta(
        debugName: "echo_test",
        argNames: ["relayUrl", "serverNpub", "timeoutMs"],
      );

  @override
  String crateApiPing() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiPingConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPingConstMeta => const TaskConstMeta(
        debugName: "ping",
        argNames: [],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BootstrapResult dco_decode_bootstrap_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return BootstrapResult(
      bootstrapRttMs: dco_decode_i_64(arr[0]),
      relayUrl: dco_decode_String(arr[1]),
      serverNpub: dco_decode_String(arr[2]),
      clientNpub: dco_decode_String(arr[3]),
      serverInfo: dco_decode_server_info(arr[4]),
    );
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  Punch dco_decode_box_autoadd_punch(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_punch(raw);
  }

  @protected
  StunInfo dco_decode_box_autoadd_stun_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_stun_info(raw);
  }

  @protected
  EchoResult dco_decode_echo_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return EchoResult(
      echoRoundtripOk: dco_decode_bool(arr[0]),
      echoRttMs: dco_decode_opt_box_autoadd_i_64(arr[1]),
      endpoint: dco_decode_endpoint(arr[2]),
      detail: dco_decode_String(arr[3]),
    );
  }

  @protected
  Endpoint dco_decode_endpoint(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Endpoint(
      host: dco_decode_String(arr[0]),
      port: dco_decode_u_16(arr[1]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  Punch? dco_decode_opt_box_autoadd_punch(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_punch(raw);
  }

  @protected
  StunInfo? dco_decode_opt_box_autoadd_stun_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_stun_info(raw);
  }

  @protected
  Punch dco_decode_punch(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Punch(
      startAtMs: dco_decode_i_64(arr[0]),
      intervalMs: dco_decode_u_64(arr[1]),
      durationMs: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  ServerInfo dco_decode_server_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return ServerInfo(
      msgType: dco_decode_String(arr[0]),
      version: dco_decode_String(arr[1]),
      sessionId: dco_decode_String(arr[2]),
      nonce: dco_decode_String(arr[3]),
      issuedAt: dco_decode_i_64(arr[4]),
      endpoint: dco_decode_endpoint(arr[5]),
      punch: dco_decode_opt_box_autoadd_punch(arr[6]),
      stun: dco_decode_opt_box_autoadd_stun_info(arr[7]),
    );
  }

  @protected
  StunInfo dco_decode_stun_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return StunInfo(
      uri: dco_decode_String(arr[0]),
      metadataTag: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BootstrapResult sse_decode_bootstrap_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bootstrapRttMs = sse_decode_i_64(deserializer);
    var var_relayUrl = sse_decode_String(deserializer);
    var var_serverNpub = sse_decode_String(deserializer);
    var var_clientNpub = sse_decode_String(deserializer);
    var var_serverInfo = sse_decode_server_info(deserializer);
    return BootstrapResult(
        bootstrapRttMs: var_bootstrapRttMs,
        relayUrl: var_relayUrl,
        serverNpub: var_serverNpub,
        clientNpub: var_clientNpub,
        serverInfo: var_serverInfo);
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  Punch sse_decode_box_autoadd_punch(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_punch(deserializer));
  }

  @protected
  StunInfo sse_decode_box_autoadd_stun_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_stun_info(deserializer));
  }

  @protected
  EchoResult sse_decode_echo_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_echoRoundtripOk = sse_decode_bool(deserializer);
    var var_echoRttMs = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_endpoint = sse_decode_endpoint(deserializer);
    var var_detail = sse_decode_String(deserializer);
    return EchoResult(
        echoRoundtripOk: var_echoRoundtripOk,
        echoRttMs: var_echoRttMs,
        endpoint: var_endpoint,
        detail: var_detail);
  }

  @protected
  Endpoint sse_decode_endpoint(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_host = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    return Endpoint(host: var_host, port: var_port);
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Punch? sse_decode_opt_box_autoadd_punch(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_punch(deserializer));
    } else {
      return null;
    }
  }

  @protected
  StunInfo? sse_decode_opt_box_autoadd_stun_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_stun_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Punch sse_decode_punch(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_startAtMs = sse_decode_i_64(deserializer);
    var var_intervalMs = sse_decode_u_64(deserializer);
    var var_durationMs = sse_decode_u_64(deserializer);
    return Punch(
        startAtMs: var_startAtMs,
        intervalMs: var_intervalMs,
        durationMs: var_durationMs);
  }

  @protected
  ServerInfo sse_decode_server_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_msgType = sse_decode_String(deserializer);
    var var_version = sse_decode_String(deserializer);
    var var_sessionId = sse_decode_String(deserializer);
    var var_nonce = sse_decode_String(deserializer);
    var var_issuedAt = sse_decode_i_64(deserializer);
    var var_endpoint = sse_decode_endpoint(deserializer);
    var var_punch = sse_decode_opt_box_autoadd_punch(deserializer);
    var var_stun = sse_decode_opt_box_autoadd_stun_info(deserializer);
    return ServerInfo(
        msgType: var_msgType,
        version: var_version,
        sessionId: var_sessionId,
        nonce: var_nonce,
        issuedAt: var_issuedAt,
        endpoint: var_endpoint,
        punch: var_punch,
        stun: var_stun);
  }

  @protected
  StunInfo sse_decode_stun_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_uri = sse_decode_String(deserializer);
    var var_metadataTag = sse_decode_opt_String(deserializer);
    return StunInfo(uri: var_uri, metadataTag: var_metadataTag);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_bootstrap_result(
      BootstrapResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.bootstrapRttMs, serializer);
    sse_encode_String(self.relayUrl, serializer);
    sse_encode_String(self.serverNpub, serializer);
    sse_encode_String(self.clientNpub, serializer);
    sse_encode_server_info(self.serverInfo, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_punch(Punch self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_punch(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_stun_info(
      StunInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_stun_info(self, serializer);
  }

  @protected
  void sse_encode_echo_result(EchoResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.echoRoundtripOk, serializer);
    sse_encode_opt_box_autoadd_i_64(self.echoRttMs, serializer);
    sse_encode_endpoint(self.endpoint, serializer);
    sse_encode_String(self.detail, serializer);
  }

  @protected
  void sse_encode_endpoint(Endpoint self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.host, serializer);
    sse_encode_u_16(self.port, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_punch(Punch? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_punch(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_stun_info(
      StunInfo? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_stun_info(self, serializer);
    }
  }

  @protected
  void sse_encode_punch(Punch self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.startAtMs, serializer);
    sse_encode_u_64(self.intervalMs, serializer);
    sse_encode_u_64(self.durationMs, serializer);
  }

  @protected
  void sse_encode_server_info(ServerInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.msgType, serializer);
    sse_encode_String(self.version, serializer);
    sse_encode_String(self.sessionId, serializer);
    sse_encode_String(self.nonce, serializer);
    sse_encode_i_64(self.issuedAt, serializer);
    sse_encode_endpoint(self.endpoint, serializer);
    sse_encode_opt_box_autoadd_punch(self.punch, serializer);
    sse_encode_opt_box_autoadd_stun_info(self.stun, serializer);
  }

  @protected
  void sse_encode_stun_info(StunInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.uri, serializer);
    sse_encode_opt_String(self.metadataTag, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
