// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BootstrapResult dco_decode_bootstrap_result(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  Punch dco_decode_box_autoadd_punch(dynamic raw);

  @protected
  StunInfo dco_decode_box_autoadd_stun_info(dynamic raw);

  @protected
  EchoResult dco_decode_echo_result(dynamic raw);

  @protected
  Endpoint dco_decode_endpoint(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  Punch? dco_decode_opt_box_autoadd_punch(dynamic raw);

  @protected
  StunInfo? dco_decode_opt_box_autoadd_stun_info(dynamic raw);

  @protected
  Punch dco_decode_punch(dynamic raw);

  @protected
  ServerInfo dco_decode_server_info(dynamic raw);

  @protected
  StunInfo dco_decode_stun_info(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BootstrapResult sse_decode_bootstrap_result(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  Punch sse_decode_box_autoadd_punch(SseDeserializer deserializer);

  @protected
  StunInfo sse_decode_box_autoadd_stun_info(SseDeserializer deserializer);

  @protected
  EchoResult sse_decode_echo_result(SseDeserializer deserializer);

  @protected
  Endpoint sse_decode_endpoint(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  Punch? sse_decode_opt_box_autoadd_punch(SseDeserializer deserializer);

  @protected
  StunInfo? sse_decode_opt_box_autoadd_stun_info(SseDeserializer deserializer);

  @protected
  Punch sse_decode_punch(SseDeserializer deserializer);

  @protected
  ServerInfo sse_decode_server_info(SseDeserializer deserializer);

  @protected
  StunInfo sse_decode_stun_info(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_bootstrap_result(
      BootstrapResult self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_punch(Punch self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_stun_info(
      StunInfo self, SseSerializer serializer);

  @protected
  void sse_encode_echo_result(EchoResult self, SseSerializer serializer);

  @protected
  void sse_encode_endpoint(Endpoint self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_punch(Punch? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_stun_info(
      StunInfo? self, SseSerializer serializer);

  @protected
  void sse_encode_punch(Punch self, SseSerializer serializer);

  @protected
  void sse_encode_server_info(ServerInfo self, SseSerializer serializer);

  @protected
  void sse_encode_stun_info(StunInfo self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;
}
